/* eslint-disable @typescript-eslint/no-explicit-any -- 测评记录兼容不同课次题目结构 */
import { ArrowLeft, CheckCircle2, ClipboardCheck, Code2, History, LoaderCircle, Play, RotateCcw, Trophy, XCircle } from 'lucide-react'
import { useMemo, useState } from 'react'
import { studentAction, type FeatureAssessment, type StudentFeatureState } from '../../lib/featureApi'
import { runPythonCode } from '../../lib/pythonRuntime'

type ProgramAnswer={code:string;output:string}
type AnswerValue=string|ProgramAnswer

export default function AssessmentCenter({features,onRefresh,onBack}:{studentId:string;features:StudentFeatureState|null;onRefresh:()=>Promise<void>;onBack:()=>void}){
  const [active,setActive]=useState<FeatureAssessment|null>(null);const [answers,setAnswers]=useState<Record<string,AnswerValue>>({});const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [running,setRunning]=useState('')
  const latest=useMemo(()=>{const map:Record<string,any>={};for(const item of features?.attempts||[])if(!map[item.assessment_id])map[item.assessment_id]=item;return map},[features])
  const totalPoints=(assessment:FeatureAssessment)=>assessment.questions.reduce((sum,q)=>sum+(q.points??10),0)
  const begin=(assessment:FeatureAssessment)=>{setActive(assessment);setResult(null);setAnswers(Object.fromEntries(assessment.questions.filter(q=>q.type==='programming').map(q=>[q.id,{code:q.starterCode||'',output:''}])))}
  const run=async(questionId:string)=>{const answer=answers[questionId] as ProgramAnswer;setRunning(questionId);try{const output=await runPythonCode(answer.code);setAnswers(current=>({...current,[questionId]:{...answer,output}}))}catch(reason){setAnswers(current=>({...current,[questionId]:{...answer,output:`运行出错：${reason instanceof Error?reason.message:String(reason)}`}}))}finally{setRunning('')}}
  const ready=Boolean(active)&&active!.questions.every(q=>q.type==='programming'?Boolean((answers[q.id] as ProgramAnswer|undefined)?.code.trim())&&Object.prototype.hasOwnProperty.call(answers[q.id]||{},'output'):Boolean(answers[q.id]))
  const submit=async()=>{if(!active)return;setBusy(true);try{const saved=await studentAction(`/student/assessments/${active.id}/submit`,'POST',{answers});setResult(saved);await onRefresh()}catch(reason){alert(reason instanceof Error?reason.message:'提交失败')}finally{setBusy(false)}}
  if(!active)return <main className="student-module-page"><header><button onClick={onBack}><ArrowLeft/>返回冒险大厅</button><div><small>ASSESSMENT CENTER</small><h1>课程测评</h1><p>可以重复作答，系统保留每次成绩，当前成绩以最近一次为准。</p></div></header><div className="assessment-card-grid">{(features?.assessments||[]).map(item=>{const last=latest[item.id];const count=(features?.attempts||[]).filter(a=>a.assessment_id===item.id).length;return <article key={item.id}><span><ClipboardCheck/></span><h2>{item.title}</h2><p>{item.description}</p><div><b>{item.questions.length} 道题 · {totalPoints(item)}分</b><em>{last?`最近 ${last.score}/${last.total}`:'尚未作答'}</em></div><button onClick={()=>begin(item)}>{last?<><RotateCcw/>再次作答（第{count+1}次）</>:<>开始测评</>}</button></article>})}{!features?.assessments.length&&<div className="portal-empty"><ClipboardCheck/><strong>老师还没有开放测评</strong><span>开放后会显示在这里。</span></div>}</div><section className="attempt-history"><h2><History/>我的历史成绩</h2>{(features?.attempts||[]).map(item=><div key={item.id}><strong>{item.score}/{item.total}</strong><span>第{item.attempt}次</span><small>{new Date(item.submitted_at).toLocaleString('zh-CN')} · 错{item.wrong.length}题</small></div>)}</section></main>
  return <main className="student-module-page assessment-taking"><header><button onClick={()=>setActive(null)}><ArrowLeft/>返回测评列表</button><div><small>QUIZ TIME</small><h1>{active.title}</h1><p>满分{totalPoints(active)}分；编程题先在浏览器运行，再统一提交。</p></div></header><div className="assessment-sheet">{active.questions.map((q,index)=>{const wrong=result?.wrong?.some((w:any)=>w.questionId===q.id);const program=q.type==='programming';const programAnswer=(answers[q.id] as ProgramAnswer|undefined)||{code:q.starterCode||'',output:''};return <article className={`${result?(wrong?'answer-wrong':'answer-correct'):''} ${program?'programming-question':''}`} key={q.id}><header><span>{String(index+1).padStart(2,'0')}</span><h2>{q.title}<small>{q.points??10} 分</small></h2>{result&&(wrong?<XCircle/>:<CheckCircle2/>)}</header>{program?<div className="assessment-code-lab"><div className="assessment-code-editor"><div><Code2/>Python代码</div><textarea spellCheck={false} disabled={Boolean(result)} value={programAnswer.code} onChange={e=>setAnswers({...answers,[q.id]:{code:e.target.value,output:''}})}/><button type="button" disabled={Boolean(result)||running===q.id} onClick={()=>run(q.id)}>{running===q.id?<LoaderCircle className="spin"/>:<Play/>}{running===q.id?'运行中…':'运行程序'}</button></div><div className="assessment-code-output"><strong>运行结果</strong><pre>{programAnswer.output||'运行后在这里查看输出。'}</pre></div></div>:<div>{(q.options||[]).map(option=><label key={option}><input type="radio" name={q.id} checked={answers[q.id]===option} onChange={()=>setAnswers({...answers,[q.id]:option})} disabled={Boolean(result)}/><span>{option}</span></label>)}</div>}{wrong&&<p>{program?'程序输出与题目要求还不一致，请修改后再次作答。':`正确答案：${result.wrong.find((w:any)=>w.questionId===q.id)?.answer}`}</p>}</article>})}<footer>{result?<div className="assessment-result"><Trophy/><strong>{result.score} / {result.total}</strong><span>第 {result.attempt} 次作答 · 错 {result.wrong.length} 题</span><button onClick={()=>begin(active)}><RotateCcw/>重新作答</button></div>:<button className="student-primary" disabled={busy||!ready} onClick={submit}>{busy?'提交中…':'提交测评'}</button>}</footer></div></main>
}
