import { ArrowLeft, CheckCircle2, Clock3, MessageCircleMore, Plus, Send, XCircle } from 'lucide-react'
import { useState } from 'react'
import { studentAction, type StudentFeatureState } from '../../lib/featureApi'

export default function CommunitySquare({features,onRefresh,onBack}:{studentId:string;studentName:string;features:StudentFeatureState|null;onRefresh:()=>Promise<void>;onBack:()=>void}){
  const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [busy,setBusy]=useState(false)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await studentAction('/student/plaza-posts','POST',{title,content,attachments:[]});setTitle('');setContent('');setOpen(false);await onRefresh();alert('作品已提交，等待老师审核。')}catch(reason){alert(reason instanceof Error?reason.message:'提交失败')}finally{setBusy(false)}}
  return <main className="student-module-page"><header><button onClick={onBack}><ArrowLeft/>返回冒险大厅</button><div><small>CREATIVE SQUARE</small><h1>交流广场</h1><p>分享作品、等待老师审核，也能看到退回修改的原因。</p></div><button className="student-primary" onClick={()=>setOpen(!open)}><Plus/>发布作品</button></header>{open&&<form className="square-compose" onSubmit={submit}><label>作品标题<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>作品介绍<textarea rows={5} value={content} onChange={e=>setContent(e.target.value)} required/></label><button className="student-primary" disabled={busy}><Send/>{busy?'提交中…':'提交审核'}</button></form>}<div className="square-grid">{(features?.posts||[]).map(post=><article key={post.id}><header><span>{post.student_name?.slice(-1)||'我'}</span><div><strong>{post.student_name||'我的作品'}</strong><small>{new Date(post.created_at).toLocaleString('zh-CN')}</small></div>{post.status==='approved'?<em className="approved"><CheckCircle2/>已展示</em>:post.status==='rejected'?<em className="rejected"><XCircle/>已退回</em>:<em><Clock3/>待审核</em>}</header><h2>{post.title}</h2><p>{post.content}</p>{post.status==='rejected'&&<aside>老师的修改建议：{post.reject_reason}</aside>}<footer><MessageCircleMore/>交流广场作品</footer></article>)}</div></main>
}
