import { CalendarDays, Check, Code2, ExternalLink, Heart, ImagePlus, LoaderCircle, MessageCircle, Play, Plus, Send, Sparkles, Trophy, UsersRound } from 'lucide-react'
import { useMemo, useState } from 'react'
import { createId, getLearningState, saveLearningState, type PlazaPost } from '../../lib/studentLearningStore'
import { runPythonCode } from '../../lib/pythonRuntime'
import { uploadPublicFile } from '../../lib/uploads'
import { ModuleHeading } from './AssessmentCenter'

export default function CommunitySquare({ studentId, studentName, onBack }: { studentId:string; studentName:string; onBack:()=>void }) {
  const [state,setState]=useState(getLearningState); const [creating,setCreating]=useState(false); const [runningPost,setRunningPost]=useState<string|null>(null); const [outputs,setOutputs]=useState<Record<string,string>>({}); const [comments,setComments]=useState<Record<string,string>>({})
  const approved=useMemo(()=>state.plazaPosts.filter((item)=>item.approved),[state]); const pending=state.plazaPosts.filter((item)=>item.studentId===studentId&&!item.approved)
  const persist=(next:typeof state)=>{saveLearningState(next);setState(next)}
  const like=(postId:string)=>{const next=getLearningState();const post=next.plazaPosts.find((item)=>item.id===postId);if(!post)return;post.likedBy=post.likedBy.includes(studentId)?post.likedBy.filter((id)=>id!==studentId):[...post.likedBy,studentId];persist(next)}
  const comment=(postId:string)=>{const content=comments[postId]?.trim();if(!content)return;const next=getLearningState();next.plazaPosts.find((item)=>item.id===postId)?.comments.push({id:createId('comment'),studentId,studentName,content,createdAt:new Date().toISOString()});persist(next);setComments((current)=>({...current,[postId]:''}))}
  const removeComment=(postId:string,commentId:string)=>{const next=getLearningState();const post=next.plazaPosts.find((item)=>item.id===postId);if(post)post.comments=post.comments.filter((item)=>item.id!==commentId);persist(next)}
  const run=async(post:PlazaPost)=>{setRunningPost(post.id);setOutputs((current)=>({...current,[post.id]:'正在启动 Python…'}));try{const output=await runPythonCode(post.code,(value)=>setOutputs((current)=>({...current,[post.id]:value})));setOutputs((current)=>({...current,[post.id]:output}))}catch(reason){setOutputs((current)=>({...current,[post.id]:`运行出错：${reason instanceof Error?reason.message:String(reason)}`}))}finally{setRunningPost(null)}}
  const register=(activityId:string)=>{const next=getLearningState();const activity=next.activities.find((item)=>item.id===activityId);if(!activity)return;activity.registeredStudentIds=activity.registeredStudentIds.includes(studentId)?activity.registeredStudentIds.filter((id)=>id!==studentId):[...activity.registeredStudentIds,studentId];persist(next)}
  return <main className="student-module-page"><ModuleHeading icon={MessageCircle} label="CREATIVE SQUARE" title="交流广场" description="分享代码与作品，看看同学们正在创造什么。" onBack={onBack}/><div className="square-toolbar"><div><Sparkles/><span>优秀作品经过老师审核后展示</span></div><button type="button" onClick={()=>setCreating(true)}><Plus/>发布新作品</button></div>{pending.length>0&&<section className="pending-posts"><strong>我的待审核作品</strong>{pending.map((post)=><span key={post.id}>{post.title}<em>等待老师审核</em></span>)}</section>}<div className="square-layout"><section className="post-feed">{approved.map((post)=><article className="plaza-post" key={post.id}><header><span>{post.studentName.slice(-1)}</span><div><strong>{post.studentName}</strong><small>{new Date(post.createdAt).toLocaleDateString('zh-CN')} · Python 作品</small></div><i>已审核</i></header><h2>{post.title}</h2><p>{post.description}</p>{post.code&&<div className="post-code"><div><Code2/><span>作品代码</span><button type="button" onClick={()=>run(post)} disabled={runningPost===post.id}>{runningPost===post.id?<LoaderCircle className="spin"/>:<Play/>}运行作品</button></div><pre>{post.code}</pre>{outputs[post.id]&&<output>{outputs[post.id]}</output>}</div>}<div className="post-actions"><button type="button" className={post.likedBy.includes(studentId)?'liked':''} onClick={()=>like(post.id)}><Heart/> {post.likedBy.length}</button><span><MessageCircle/> {post.comments.length}</span></div><div className="post-comments">{post.comments.map((item)=><div key={item.id}><strong>{item.studentName}</strong><p>{item.content}</p>{item.studentId===studentId&&<button type="button" onClick={()=>removeComment(post.id,item.id)}>删除</button>}</div>)}<form onSubmit={(event)=>{event.preventDefault();comment(post.id)}}><input value={comments[post.id]||''} onChange={(event)=>setComments((current)=>({...current,[post.id]:event.target.value}))} placeholder="友善地说点什么…"/><button><Send/></button></form></div></article>)}</section><aside className="activity-rail"><div className="activity-title"><Trophy/><div><small>ACTIVITIES</small><strong>比赛与活动</strong></div></div>{state.activities.map((item)=><article key={item.id}><span><CalendarDays/> {item.date}</span><h3>{item.title}</h3><p>{item.description}</p>{item.registrationType==='external'?<a href={item.externalUrl} target="_blank" rel="noreferrer">查看活动 <ExternalLink/></a>:<button type="button" className={item.registeredStudentIds.includes(studentId)?'registered':''} onClick={()=>register(item.id)}>{item.registeredStudentIds.includes(studentId)?<><Check/>已报名</>:<><UsersRound/>站内报名</>}</button>}</article>)}</aside></div>{creating&&<CreatePost studentId={studentId} studentName={studentName} onClose={()=>setCreating(false)} onCreated={()=>{setState(getLearningState());setCreating(false)}}/>}</main>
}

function CreatePost({studentId,studentName,onClose,onCreated}:{studentId:string;studentName:string;onClose:()=>void;onCreated:()=>void}){
  const [form,setForm]=useState({title:'',description:'',code:''});const [files,setFiles]=useState<File[]>([]);const [uploading,setUploading]=useState(false)
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setUploading(true);try{const mediaNames:string[]=[];for(const file of files)mediaNames.push((await uploadPublicFile(file,`square/${studentId}`)).url);const state=getLearningState();state.plazaPosts.push({id:createId('post'),studentId,studentName,...form,mediaNames,approved:false,createdAt:new Date().toISOString(),likedBy:[],comments:[]});saveLearningState(state);onCreated()}catch(reason){window.alert(reason instanceof Error?reason.message:'作品附件上传失败。')}finally{setUploading(false)}}
  return <div className="quest-modal-backdrop" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose()}}><form className="create-post-modal" onSubmit={submit}><div><span>NEW CREATION</span><h2>发布新作品</h2><p>提交后由老师审核，审核通过后会出现在交流广场。</p></div><label>作品标题<input value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})} required placeholder="给作品起一个响亮的名字"/></label><label>作品说明<textarea rows={3} value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})} required placeholder="介绍作品玩法和你的创作思路"/></label><label>Python 代码<textarea rows={9} className="post-code-input" value={form.code} onChange={(event)=>setForm({...form,code:event.target.value})} placeholder="# 可以粘贴能够运行的 Python 代码"/></label><label className="post-file-picker"><ImagePlus/>选择图片或视频<input hidden multiple type="file" accept="image/*,video/*" onChange={(event)=>setFiles(Array.from(event.target.files||[]).slice(0,10))}/></label>{files.length>0&&<p className="selected-files">已选择：{files.map((file)=>file.name).join('、')}</p>}<div className="create-post-actions"><button type="button" onClick={onClose}>取消</button><button type="submit" disabled={uploading}>{uploading?<LoaderCircle className="spin"/>:<Send/>}{uploading?'正在上传…':'提交审核'}</button></div></form></div>
}
