/* eslint-disable @typescript-eslint/no-explicit-any -- 作业题型和旧提交结构可扩展 */
import { ArrowLeft, CheckCircle2, FileArchive, FileCode2, Image, Save, Upload, Video } from 'lucide-react'
import { useState } from 'react'
import RichContent from '../../components/RichContent'
import { studentAction, uploadStudentSharedFile, type StudentFeatureState } from '../../lib/featureApi'

export default function HomeworkCenter({features,onRefresh,onBack}:{studentId:string;studentName:string;features:StudentFeatureState|null;onRefresh:()=>Promise<void>;onBack:()=>void}){
  const [active,setActive]=useState<any>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [code,setCode]=useState('');const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false)
  const existing=active?(features?.submissions||[]).find(s=>s.homework_id===active.id):null
  const open=(item:any)=>{setActive(item);const saved=(features?.submissions||[]).find(s=>s.homework_id===item.id);setAnswers(saved?.answers?.values||{main:saved?.answers?.text||''});setCode(saved?.answers?.code||'');setFiles([])}
  const submit=async()=>{if(!active||!features)return;setBusy(true);try{const attachments=[];for(const file of files)attachments.push(await uploadStudentSharedFile(file,features.classId,'homework'));await studentAction(`/student/homework/${active.id}`,'PUT',{answers:{values:answers,code},attachments:[...(existing?.attachments||[]),...attachments]});await onRefresh();alert(existing?'作业已更新，老师之前的评分与评语已保留。':'作业提交成功。');setActive(null)}catch(reason){alert(reason instanceof Error?reason.message:'提交失败')}finally{setBusy(false)}}
  if(active)return <main className="student-module-page"><header><button onClick={()=>setActive(null)}><ArrowLeft/>返回作业列表</button><div><small>HOMEWORK EDITOR</small><h1>{active.title}</h1><RichContent html={active.description}/></div></header><section className="student-homework-editor">{active.questions?.map((q:any)=><fieldset className="homework-question" key={q.id}><legend>{q.title}</legend>{q.type==='choice'?<div>{(q.options||[]).map((option:string)=><label key={option}><input type="radio" name={q.id} checked={answers[q.id]===option} onChange={()=>setAnswers({...answers,[q.id]:option})}/>{option}</label>)}</div>:<textarea value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} rows={5}/>}</fieldset>)}{!active.questions?.length&&<label>文字回答 / 作品说明<textarea value={answers.main||''} onChange={e=>setAnswers({...answers,main:e.target.value})} rows={5}/></label>}<label>Python代码（普通Python，不加载Turtle和Pygame）<textarea className="code-answer" value={code} onChange={e=>setCode(e.target.value)} rows={10} spellCheck={false}/></label><label className="student-file-picker"><Upload/>添加附件<input hidden multiple type="file" accept="image/*,video/*,.py,.zip,application/zip" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><div className="selected-files">{files.map(file=><span key={file.name}>{file.name}</span>)}</div>{existing&&<aside className="previous-feedback"><CheckCircle2/><div><strong>老师评分：{existing.score??'待评分'}</strong><p>{existing.feedback||'老师还没有填写评语'}</p></div></aside>}<button className="student-primary" disabled={busy} onClick={submit}><Save/>{busy?'正在保存…':existing?'更新我的作业':'提交作业'}</button></section></main>
  return <main className="student-module-page"><header><button onClick={onBack}><ArrowLeft/>返回冒险大厅</button><div><small>MY HOMEWORK</small><h1>每日作业</h1><p>支持文字、图片、视频、Python文件和ZIP；提交后可一直修改。</p></div></header><div className="homework-card-grid">{(features?.homework||[]).map(item=>{const saved=(features?.submissions||[]).find(s=>s.homework_id===item.id);return <article key={item.id}><span><FileCode2/></span><h2>{item.title}</h2><RichContent html={item.description} className="homework-description-preview"/><div className="homework-types"><em><Image/>图片</em><em><Video/>视频</em><em><FileCode2/>PY</em><em><FileArchive/>ZIP</em></div>{saved&&<small>已提交 · {saved.score==null?'等待老师评分':`${saved.score}分`}</small>}<button onClick={()=>open(item)}>{saved?'继续修改':'开始作业'}</button></article>})}{!features?.homework.length&&<div className="portal-empty"><FileCode2/><strong>暂时没有新作业</strong><span>老师发布后会自动出现在这里。</span></div>}</div></main>
}
