import { CalendarDays, ClipboardList, Plus, Save } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { EmptyState, PageLoader } from '../../../components/States'
import RichContent from '../../../components/RichContent'
import RichTextEditor from '../../../components/admin/RichTextEditor'
import { adminAction, getAdminFeatureState, type FeatureState } from '../../../lib/featureApi'

export default function HomeworkPanelV2({classId,termId}:{classId:string;termId:string}){
  const [state,setState]=useState<FeatureState|null>(null);const [form,setForm]=useState({title:'',description:'',dueAt:'',question:'',questionType:'text',options:''});const [saving,setSaving]=useState(false)
  const load=useCallback(async()=>{if(classId)setState(await getAdminFeatureState(classId))},[classId]);useEffect(()=>{load()},[load])
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const options=form.options.split(/[，,\n]/).map(item=>item.trim()).filter(Boolean);await adminAction('/admin/homework','POST',{classId,termId,title:form.title,description:form.description,dueAt:form.dueAt||null,questions:form.question?[{id:`q-${Date.now()}`,type:form.questionType,title:form.question,options:form.questionType==='choice'?options:[]}]:[]});setForm({title:'',description:'',dueAt:'',question:'',questionType:'text',options:''});await load()}catch(reason){alert(reason instanceof Error?reason.message:'发布失败')}finally{setSaving(false)}}
  if(!classId||!termId)return <EmptyState title="请先选择班级和学期" description="每日作业会按班级同步到学生端。"/>
  return <div><div className="admin-page-heading"><div><small>DAILY HOMEWORK</small><h1>每日作业</h1><p>这里是唯一的作业发布入口，发布后学生端自动出现。</p></div></div><section className="portal-admin-card"><header><div><ClipboardList/><span><strong>布置今日作业</strong><small>支持富文本、图片、代码块、文字回答和选择题。</small></span></div></header><form className="assignment-create" onSubmit={submit}><label>作业标题<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><RichTextEditor label="作业说明（支持图片与代码块）" value={form.description} onChange={description=>setForm(current=>({...current,description}))} uploadFolder={`homework/${classId}/${termId}`} minHeight={150}/><div className="assignment-question-row"><label>题目类型<select value={form.questionType} onChange={e=>setForm({...form,questionType:e.target.value})}><option value="text">文字回答</option><option value="choice">选择题</option></select></label><label>题目内容<input value={form.question} onChange={e=>setForm({...form,question:e.target.value})} placeholder="例如：input()返回的数据是什么类型？"/></label>{form.questionType==='choice'&&<label>选项（逗号分隔）<input value={form.options} onChange={e=>setForm({...form,options:e.target.value})} placeholder="字符串,整数,小数"/></label>}</div><div className="assignment-publish-row"><label>截止时间<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><button className="admin-primary" disabled={saving}><Plus/>{saving?'发布中…':'发布到学生端'}</button></div></form></section>{!state?<PageLoader label="正在读取作业…"/>:state.homework.length?<div className="admin-list-stack homework-sync-list">{state.homework.map(item=><div key={item.id}><span className="file-tile"><ClipboardList/></span><div><strong>{item.title}</strong><RichContent html={item.description} className="homework-admin-preview"/></div><em>{state.submissions.filter(s=>s.homework_id===item.id).length} 人已提交</em><span className="published"><Save/>已同步</span>{item.due_at&&<small><CalendarDays/>{new Date(item.due_at).toLocaleString('zh-CN')}</small>}</div>)}</div>:<EmptyState title="还没有作业" description="上方发布后，会同步出现在学生端作业模块。"/>}</div>
}
